image: node:18

stages:
  - e2e

e2e-tests:
  stage: e2e
  when: manual   # equivalente ao workflow_dispatch (execução manual)

  script:
    - echo "Instalando dependências"
    - yarn install
  
    - echo "Instalando browser do Playwright" # equivalente ao comando yarn playwright
    - npx playwright install --with-deps

    - echo "Executando testes e2e"
    - yarn run e2e
