#CI de nivel 01 - Disparo manual através de clique
#nome da pipeline
name: 'Execução Manual'

#gatilho / triggers - regras de disparo
#gatilho manual = workflow_dispatch
on:
  workflow_dispatch:

  push:
    branches:
      - master

#jobs - tarefas dentro da pipeline
jobs:
  #nome do job
  e2e-tests:
    #maquina onde o job vai rodar
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy

    #passos do job
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      #instalação do Yarn
      - name: Instalando o Yarn
        run: npm install -g yarn

      #instalação das dependências
      - name: Instalando dependências
        run: yarn

      #instalação do browser do playwright
      - name: Instalando o browser do Playwright
        run: npx playwright install --with-deps

      - name: Verificar Playwright
        run: npx playwright --version

      #execução dos testes e2e
      - name: Executando os testes e2e
        run: yarn run e2e

      - name: Converter para CTRF
        run: npx ctrf ./ctrf/report.json -o ./ctrf/ctrf-report.json

      - name: Publish Test Report
        if: always()
        uses: ctrf-io/github-test-reporter@v1
        with:
        report-path: './ctrf/ctrf-report.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-report: true
        summary-report: true

      - name: Salvando relatórios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report
          name: Relatório de Testes E2E
