#CI de nivel 02 - Disparo agendado
#nome da pipeline
name: 'Schedule Execution '

#gatilho / triggers - regras de disparo
#gatilho manual = workflow_dispatch
on:
  schedule:
# cronograma de execução - formato cron
# 1 - minuto, 2 - hora, 3 - dia do mês, 4 - mês, 5 - dia da semana
    - cron: '*/5 * * * *' # Executa a cada 5 minutos

#jobs - tarefas dentro da pipeline
jobs:
  #nome do job
  e2e-tests:

    #maquina onde o job vai rodar
    runs-on: ubuntu-latest

    #passos do job
    steps:
      #clone do projeto
      - uses: actions/checkout@v4
      
      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      #instalação do Yarn
      - name: Instalando o Yarn
        run: npm install -g yarn

      #instalação das dependências
      - name: Instalando dependências
        run: yarn

      #instalação do browser do playwright
      - name: Instalando o browser do Playwright
        run: yarn playwright install

      #execução dos testes e2e
      - name: Executando os testes e2e
        run: yarn run e2e